name: check_code_quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
          pip install -r requirements.txt
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
            for changed_file in ${{ steps.files.outputs.all }}; do
                python promptsource/show_templates.py ${changed_file}
            done
